GET {{URL}}/books

###
POST {{URL}}/books
Content-Type: application/json

{
    "title": "BookFromHttp",
    "author": "FromHttp"
}

###
GET {{URL}}/books/1

###
PUT {{URL}}/books/2
Content-Type: application/json

{
  "title": "BookUpdated2",
  "author": "Updated"
}

###
DELETE {{URL}}/books/6